name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install packages
      run: npm ci
    # - name: Run tests
    #   run: npm test
    - name: Build
      run: npm build


    # steps:
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag sprintcards:$(date +%s)

    # steps:
    #   - name: Check out the repo
    #     uses: actions/checkout@v2
    #   - name: Push to Docker Hub
    #     uses: docker/build-push-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #       repository: murrayjack/sprintcards
    #       tag_with_ref: true